# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d57b85e40592cf47d44dacf6d204f7b4df84fa6296a9525319180bdcf9124d955879b7ff7cb26f105c28ebe70029e1185e61f346425aec0cc1a17996edf2433f

test:
  secret_key_base: fcaf17059d6a3164fa8aa04eee14951dd159bcc2934d808822dba130b6b43fa1afb5b2552e2b6f648b70233426bd1c6bde656eab053d981c00dd610ed5183d69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
